# Generated by Django 5.2.13 on 2026-04-29 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_badge_userlevel_userbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('uzcard', 'Uzcard'), ('humo', 'Humo'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('click', 'Click'), ('payme', 'Payme')], max_length=20)),
                ('card_number', models.CharField(max_length=19)),
                ('card_holder', models.CharField(max_length=100)),
                ('expiry_date', models.CharField(max_length=5)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Card',
                'verbose_name_plural': 'Payment Cards',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
