# Generated by Django 4.2.7 on 2026-05-31 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_shopitem_user_coins_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_wallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
