# Generated by Django 5.2.13 on 2026-04-29 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['lesson__order'], 'verbose_name': 'Lesson Progress', 'verbose_name_plural': 'Lesson Progress'},
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='last_position',
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='watch_time',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LiveLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=60, help_text='Davomiyligi (daqiqa)')),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('live', 'Jonli'), ('ended', 'Tugagan'), ('cancelled', 'Bekor qilingan')], default='scheduled', max_length=20)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom/Google Meet link')),
                ('max_participants', models.IntegerField(default=50)),
                ('is_recorded', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_lessons', to='courses.course')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_live_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Lesson',
                'verbose_name_plural': 'Live Lessons',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='LiveLessonParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('live_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='courses.livelesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_lesson_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Lesson Participant',
                'verbose_name_plural': 'Live Lesson Participants',
                'unique_together': {('live_lesson', 'user')},
            },
        ),
    ]
