# Generated by Django 4.2.7 on 2026-05-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('click', 'Click'), ('payme', 'Payme'), ('uzcard', 'Uzcard'), ('humo', 'Humo'), ('cash', 'Naqd'), ('wallet', 'Wallet')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Kutilmoqda'), ('paid', "To'landi"), ('failed', 'Xatolik'), ('cancelled', 'Bekor qilindi'), ('overdue', "Muddati o'tdi")], default='pending', max_length=20),
        ),
    ]
