from django.core.management.base import BaseCommand
from apps.courses.models import EducationalCenter
import random


class Command(BaseCommand):
    help = 'Add sample educational centers'

    def handle(self, *args, **kwargs):
        centers_data = [
            {
                'name': 'IT Academy',
                'slug': 'it-academy',
                'short_description': 'IT va dasturlash bo\'yicha eng yaxshi o\'quv markazi',
                'description': 'IT Academy - bu IT va dasturlash bo\'yicha eng yaxshi o\'quv markazi. Biz Python, JavaScript, Java, C++ va boshqa ko\'plab dasturlash tillarini o\'rgatamiz. Shuningdek, web development, mobile development, data science va AI bo\'yicha kurslarimiz mavjud.',
                'phone': '+998 71 200 00 00',
                'email': 'info@itacademy.uz',
                'address': 'Toshkent sh., Amir Temur ko\'chasi, 107A',
                'city': 'Toshkent',
                'website': 'https://itacademy.uz',
                'telegram': 'https://t.me/itacademy',
                'instagram': 'https://instagram.com/itacademy',
                'facebook': 'https://facebook.com/itacademy',
                'rating': 4.8,
                'reviews_count': 245,
                'students_count': 1500,
                'courses_count': 25,
                'is_featured': True,
            },
            {
                'name': 'English World',
                'slug': 'english-world',
                'short_description': 'Ingliz tilini o\'rganish uchun eng yaxshi joy',
                'description': 'English World - bu ingliz tilini o\'rganish uchun eng yaxshi o\'quv markazi. Biz IELTS, TOEFL, General English va Business English kurslarini taklif etamiz. Tajribali o\'qituvchilar va zamonaviy uslublar bilan tilni tez o\'rganing.',
                'phone': '+998 71 234 56 78',
                'email': 'info@englishworld.uz',
                'address': 'Toshkent sh., Mustaqillik ko\'chasi, 45',
                'city': 'Toshkent',
                'website': 'https://englishworld.uz',
                'telegram': 'https://t.me/englishworld',
                'instagram': 'https://instagram.com/englishworld',
                'facebook': 'https://facebook.com/englishworld',
                'rating': 4.7,
                'reviews_count': 189,
                'students_count': 1200,
                'courses_count': 15,
                'is_featured': True,
            },
            {
                'name': 'Design Hub',
                'slug': 'design-hub',
                'short_description': 'Grafik dizayn va UI/UX bo\'yicha professional kurslar',
                'description': 'Design Hub - bu grafik dizayn va UI/UX bo\'yicha professional kurslar. Adobe Photoshop, Illustrator, Figma, Sketch va boshqa dizayn dasturlarini o\'rganing. Bizda tajribali dizaynerlar o\'qitadi.',
                'phone': '+998 71 345 67 89',
                'email': 'info@designhub.uz',
                'address': 'Toshkent sh., Bunyodkor ko\'chasi, 23',
                'city': 'Toshkent',
                'website': 'https://designhub.uz',
                'telegram': 'https://t.me/designhub',
                'instagram': 'https://instagram.com/designhub',
                'facebook': 'https://facebook.com/designhub',
                'rating': 4.6,
                'reviews_count': 156,
                'students_count': 800,
                'courses_count': 12,
                'is_featured': True,
            },
            {
                'name': 'Marketing Pro',
                'slug': 'marketing-pro',
                'short_description': 'Digital marketing va biznes bo\'yicha kurslar',
                'description': 'Marketing Pro - bu digital marketing va biznes bo\'yicha kurslar. SEO, SMM, Google Ads, Facebook Ads, email marketing va boshqa marketing yo\'nalishlarini o\'rganing. Bizda amaliy loyihalar va case studies mavjud.',
                'phone': '+998 71 456 78 90',
                'email': 'info@marketingpro.uz',
                'address': 'Toshkent sh., Navoiy ko\'chasi, 67',
                'city': 'Toshkent',
                'website': 'https://marketingpro.uz',
                'telegram': 'https://t.me/marketingpro',
                'instagram': 'https://instagram.com/marketingpro',
                'facebook': 'https://facebook.com/marketingpro',
                'rating': 4.5,
                'reviews_count': 134,
                'students_count': 650,
                'courses_count': 10,
                'is_featured': False,
            },
            {
                'name': 'Finance Academy',
                'slug': 'finance-academy',
                'short_description': 'Moliya va buxgalteriya bo\'yicha professional kurslar',
                'description': 'Finance Academy - bu moliya va buxgalteriya bo\'yicha professional kurslar. Buxgalteriya, moliya tahlili, investitsiya va boshqa moliya yo\'nalishlarini o\'rganing. Bizda tajribali moliya mutaxassislar o\'qitadi.',
                'phone': '+998 71 567 89 01',
                'email': 'info@financeacademy.uz',
                'address': 'Toshkent sh., O\'zbekiston ko\'chasi, 89',
                'city': 'Toshkent',
                'website': 'https://financeacademy.uz',
                'telegram': 'https://t.me/financeacademy',
                'instagram': 'https://instagram.com/financeacademy',
                'facebook': 'https://facebook.com/financeacademy',
                'rating': 4.4,
                'reviews_count': 112,
                'students_count': 500,
                'courses_count': 8,
                'is_featured': False,
            },
            {
                'name': 'Code School',
                'slug': 'code-school',
                'short_description': 'Bolalar va o\'smirlar uchun dasturlash kurslari',
                'description': 'Code School - bu bolalar va o\'smirlar uchun dasturlash kurslari. Scratch, Python, JavaScript va boshqa dasturlash tillarini o\'rganing. Bizda bolalar uchun qiziqarli va interaktiv darslar mavjud.',
                'phone': '+998 71 678 90 12',
                'email': 'info@codeschool.uz',
                'address': 'Toshkent sh., Qorasuv ko\'chasi, 34',
                'city': 'Toshkent',
                'website': 'https://codeschool.uz',
                'telegram': 'https://t.me/codeschool',
                'instagram': 'https://instagram.com/codeschool',
                'facebook': 'https://facebook.com/codeschool',
                'rating': 4.9,
                'reviews_count': 278,
                'students_count': 2000,
                'courses_count': 20,
                'is_featured': True,
            },
            {
                'name': 'Business School',
                'slug': 'business-school',
                'short_description': 'Biznes boshqaruvi va tadbirkorlik bo\'yicha kurslar',
                'description': 'Business School - bu biznes boshqaruvi va tadbirkorlik bo\'yicha kurslar. MBA, biznes strategiyasi, tadbirkorlik, menejment va boshqa biznes yo\'nalishlarini o\'rganing. Bizda tajribali biznes mutaxassislar o\'qitadi.',
                'phone': '+998 71 789 01 23',
                'email': 'info@businessschool.uz',
                'address': 'Toshkent sh., Istiqlol ko\'chasi, 12',
                'city': 'Toshkent',
                'website': 'https://businessschool.uz',
                'telegram': 'https://t.me/businessschool',
                'instagram': 'https://instagram.com/businessschool',
                'facebook': 'https://facebook.com/businessschool',
                'rating': 4.3,
                'reviews_count': 98,
                'students_count': 450,
                'courses_count': 7,
                'is_featured': False,
            },
            {
                'name': 'Language Center',
                'slug': 'language-center',
                'short_description': 'Ko\'plab tillarni o\'rganish uchun o\'quv markazi',
                'description': 'Language Center - bu ko\'plab tillarni o\'rganish uchun o\'quv markazi. Ingliz, nemis, fransuz, ispan, xitoy, koreys va boshqa tillarni o\'rganing. Bizda tajribali til o\'qituvchilari va zamonaviy o\'quv materiallari mavjud.',
                'phone': '+998 71 890 12 34',
                'email': 'info@languagecenter.uz',
                'address': 'Toshkent sh., Bobur ko\'chasi, 56',
                'city': 'Toshkent',
                'website': 'https://languagecenter.uz',
                'telegram': 'https://t.me/languagecenter',
                'instagram': 'https://instagram.com/languagecenter',
                'facebook': 'https://facebook.com/languagecenter',
                'rating': 4.2,
                'reviews_count': 87,
                'students_count': 400,
                'courses_count': 18,
                'is_featured': False,
            },
            {
                'name': 'Data Science Academy',
                'slug': 'data-science-academy',
                'short_description': 'Data science va machine learning bo\'yicha kurslar',
                'description': 'Data Science Academy - bu data science va machine learning bo\'yicha kurslar. Python, R, SQL, statistics, machine learning, deep learning va boshqa data science yo\'nalishlarini o\'rganing. Bizda amaliy loyihalar va real data sets mavjud.',
                'phone': '+998 71 901 23 45',
                'email': 'info@datascienceacademy.uz',
                'address': 'Toshkent sh., Shota Rustaveli ko\'chasi, 78',
                'city': 'Toshkent',
                'website': 'https://datascienceacademy.uz',
                'telegram': 'https://t.me/datascienceacademy',
                'instagram': 'https://instagram.com/datascienceacademy',
                'facebook': 'https://facebook.com/datascienceacademy',
                'rating': 4.7,
                'reviews_count': 167,
                'students_count': 900,
                'courses_count': 14,
                'is_featured': True,
            },
            {
                'name': 'Mobile Dev School',
                'slug': 'mobile-dev-school',
                'short_description': 'Mobile development bo\'yicha professional kurslar',
                'description': 'Mobile Dev School - bu mobile development bo\'yicha professional kurslar. iOS (Swift), Android (Kotlin), React Native, Flutter va boshqa mobile development texnologiyalarini o\'rganing. Bizda amaliy loyihalar va app development mavjud.',
                'phone': '+998 71 012 34 56',
                'email': 'info@mobiledevschool.uz',
                'address': 'Toshkent sh., Afrosiyob ko\'chasi, 90',
                'city': 'Toshkent',
                'website': 'https://mobiledevschool.uz',
                'telegram': 'https://t.me/mobiledevschool',
                'instagram': 'https://instagram.com/mobiledevschool',
                'facebook': 'https://facebook.com/mobiledevschool',
                'rating': 4.5,
                'reviews_count': 145,
                'students_count': 700,
                'courses_count': 11,
                'is_featured': False,
            },
            {
                'name': 'Web Dev Academy',
                'slug': 'web-dev-academy',
                'short_description': 'Web development bo\'yicha to\'liq kurslar',
                'description': 'Web Dev Academy - bu web development bo\'yicha to\'liq kurslar. HTML, CSS, JavaScript, React, Vue, Angular, Node.js, Django, Laravel va boshqa web texnologiyalarini o\'rganing. Bizda front-end va back-end development mavjud.',
                'phone': '+998 71 234 56 79',
                'email': 'info@webdevacademy.uz',
                'address': 'Toshkent sh., Chilanzar ko\'chasi, 11',
                'city': 'Toshkent',
                'website': 'https://webdevacademy.uz',
                'telegram': 'https://t.me/webdevacademy',
                'instagram': 'https://instagram.com/webdevacademy',
                'facebook': 'https://facebook.com/webdevacademy',
                'rating': 4.6,
                'reviews_count': 178,
                'students_count': 1100,
                'courses_count': 16,
                'is_featured': True,
            },
            {
                'name': 'Cyber Security Hub',
                'slug': 'cyber-security-hub',
                'short_description': 'Cyber security va network security bo\'yicha kurslar',
                'description': 'Cyber Security Hub - bu cyber security va network security bo\'yicha kurslar. Ethical hacking, penetration testing, network security, cloud security va boshqa security yo\'nalishlarini o\'rganing. Bizda amaliy security labs va CTF challenges mavjud.',
                'phone': '+998 71 345 67 80',
                'email': 'info@cybersecurityhub.uz',
                'address': 'Toshkent sh., Yunusobod ko\'chasi, 22',
                'city': 'Toshkent',
                'website': 'https://cybersecurityhub.uz',
                'telegram': 'https://t.me/cybersecurityhub',
                'instagram': 'https://instagram.com/cybersecurityhub',
                'facebook': 'https://facebook.com/cybersecurityhub',
                'rating': 4.4,
                'reviews_count': 123,
                'students_count': 550,
                'courses_count': 9,
                'is_featured': False,
            },
            {
                'name': 'Cloud Computing School',
                'slug': 'cloud-computing-school',
                'short_description': 'Cloud computing va DevOps bo\'yicha kurslar',
                'description': 'Cloud Computing School - bu cloud computing va DevOps bo\'yicha kurslar. AWS, Azure, GCP, Docker, Kubernetes, CI/CD va boshqa cloud va DevOps texnologiyalarini o\'rganing. Bizda amaliy cloud projects va DevOps pipelines mavjud.',
                'phone': '+998 71 456 78 91',
                'email': 'info@cloudcomputingschool.uz',
                'address': 'Toshkent sh., Yakkasaroy ko\'chasi, 33',
                'city': 'Toshkent',
                'website': 'https://cloudcomputingschool.uz',
                'telegram': 'https://t.me/cloudcomputingschool',
                'instagram': 'https://instagram.com/cloudcomputingschool',
                'facebook': 'https://facebook.com/cloudcomputingschool',
                'rating': 4.3,
                'reviews_count': 109,
                'students_count': 480,
                'courses_count': 8,
                'is_featured': False,
            },
            {
                'name': 'AI Research Lab',
                'slug': 'ai-research-lab',
                'short_description': 'Artificial Intelligence va Deep Learning bo\'yicha kurslar',
                'description': 'AI Research Lab - bu Artificial Intelligence va Deep Learning bo\'yicha kurslar. Neural networks, computer vision, NLP, reinforcement learning va boshqa AI yo\'nalishlarini o\'rganing. Bizda amaliy AI projects va research papers mavjud.',
                'phone': '+998 71 567 89 02',
                'email': 'info@airesearchlab.uz',
                'address': 'Toshkent sh., Mirzo Ulug\'bek ko\'chasi, 44',
                'city': 'Toshkent',
                'website': 'https://airesearchlab.uz',
                'telegram': 'https://t.me/airesearchlab',
                'instagram': 'https://instagram.com/airesearchlab',
                'facebook': 'https://facebook.com/airesearchlab',
                'rating': 4.8,
                'reviews_count': 156,
                'students_count': 350,
                'courses_count': 6,
                'is_featured': True,
            },
            {
                'name': 'Robotics Academy',
                'slug': 'robotics-academy',
                'short_description': 'Robotics va automation bo\'yicha kurslar',
                'description': 'Robotics Academy - bu robotics va automation bo\'yicha kurslar. Arduino, Raspberry Pi, industrial robotics, automation va boshqa robotics yo\'nalishlarini o\'rganing. Bizda amaliy robotics projects va labs mavjud.',
                'phone': '+998 71 678 90 13',
                'email': 'info@roboticsacademy.uz',
                'address': 'Toshkent sh., Zarkaynar ko\'chasi, 55',
                'city': 'Toshkent',
                'website': 'https://roboticsacademy.uz',
                'telegram': 'https://t.me/roboticsacademy',
                'instagram': 'https://instagram.com/roboticsacademy',
                'facebook': 'https://facebook.com/roboticsacademy',
                'rating': 4.5,
                'reviews_count': 134,
                'students_count': 420,
                'courses_count': 7,
                'is_featured': False,
            },
            {
                'name': 'Game Dev Studio',
                'slug': 'game-dev-studio',
                'short_description': 'Game development bo\'yicha professional kurslar',
                'description': 'Game Dev Studio - bu game development bo\'yicha professional kurslar. Unity, Unreal Engine, game design, 3D modeling, animation va boshqa game development yo\'nalishlarini o\'rganing. Bizda amaliy game projects va game jams mavjud.',
                'phone': '+998 71 789 01 24',
                'email': 'info@gamedevstudio.uz',
                'address': 'Toshkent sh., Toshkent ko\'chasi, 66',
                'city': 'Toshkent',
                'website': 'https://gamedevstudio.uz',
                'telegram': 'https://t.me/gamedevstudio',
                'instagram': 'https://instagram.com/gamedevstudio',
                'facebook': 'https://facebook.com/gamedevstudio',
                'rating': 4.6,
                'reviews_count': 167,
                'students_count': 580,
                'courses_count': 10,
                'is_featured': False,
            },
            {
                'name': 'Video Production School',
                'slug': 'video-production-school',
                'short_description': 'Video production va editing bo\'yicha kurslar',
                'description': 'Video Production School - bu video production va editing bo\'yicha kurslar. Video editing, cinematography, sound design, motion graphics va boshqa video production yo\'nalishlarini o\'rganing. Bizda amaliy video projects va professional equipment mavjud.',
                'phone': '+998 71 890 12 35',
                'email': 'info@videoproductionschool.uz',
                'address': 'Toshkent sh., Beruniy ko\'chasi, 77',
                'city': 'Toshkent',
                'website': 'https://videoproductionschool.uz',
                'telegram': 'https://t.me/videoproductionschool',
                'instagram': 'https://instagram.com/videoproductionschool',
                'facebook': 'https://facebook.com/videoproductionschool',
                'rating': 4.4,
                'reviews_count': 145,
                'students_count': 520,
                'courses_count': 9,
                'is_featured': False,
            },
            {
                'name': 'Photography Academy',
                'slug': 'photography-academy',
                'short_description': 'Fotografiya va visual arts bo\'yicha kurslar',
                'description': 'Photography Academy - bu fotografiya va visual arts bo\'yicha kurslar. Portrait photography, landscape photography, product photography, photo editing va boshqa fotografiya yo\'nalishlarini o\'rganing. Bizda amaliy photo shoots va portfolio building mavjud.',
                'phone': '+998 71 012 34 57',
                'email': 'info@photographyacademy.uz',
                'address': 'Toshkent sh., Gafur Gulom ko\'chasi, 88',
                'city': 'Toshkent',
                'website': 'https://photographyacademy.uz',
                'telegram': 'https://t.me/photographyacademy',
                'instagram': 'https://instagram.com/photographyacademy',
                'facebook': 'https://facebook.com/photographyacademy',
                'rating': 4.7,
                'reviews_count': 189,
                'students_count': 680,
                'courses_count': 12,
                'is_featured': True,
            },
            {
                'name': 'Music Production School',
                'slug': 'music-production-school',
                'short_description': 'Music production va audio engineering bo\'yicha kurslar',
                'description': 'Music Production School - bu music production va audio engineering bo\'yicha kurslar. Music production, audio engineering, sound design, mixing, mastering va boshqa music production yo\'nalishlarini o\'rganing. Bizda amaliy music projects va professional studio mavjud.',
                'phone': '+998 71 234 56 80',
                'email': 'info@musicproductionschool.uz',
                'address': 'Toshkent sh., Alisher Navoiy ko\'chasi, 99',
                'city': 'Toshkent',
                'website': 'https://musicproductionschool.uz',
                'telegram': 'https://t.me/musicproductionschool',
                'instagram': 'https://instagram.com/musicproductionschool',
                'facebook': 'https://facebook.com/musicproductionschool',
                'rating': 4.5,
                'reviews_count': 156,
                'students_count': 460,
                'courses_count': 8,
                'is_featured': False,
            },
            {
                'name': '3D Animation Studio',
                'slug': '3d-animation-studio',
                'short_description': '3D animation va VFX bo\'yicha kurslar',
                'description': '3D Animation Studio - bu 3D animation va VFX bo\'yicha kurslar. 3D modeling, animation, rigging, texturing, lighting, rendering, VFX va boshqa 3D animation yo\'nalishlarini o\'rganing. Bizda amaliy 3D projects va professional software mavjud.',
                'phone': '+998 71 345 67 81',
                'email': 'info@3danimationstudio.uz',
                'address': 'Toshkent sh., Muqimiy ko\'chasi, 101',
                'city': 'Toshkent',
                'website': 'https://3danimationstudio.uz',
                'telegram': 'https://t.me/3danimationstudio',
                'instagram': 'https://instagram.com/3danimationstudio',
                'facebook': 'https://facebook.com/3danimationstudio',
                'rating': 4.6,
                'reviews_count': 178,
                'students_count': 540,
                'courses_count': 11,
                'is_featured': False,
            },
        ]

        created_count = 0
        updated_count = 0

        for center_data in centers_data:
            slug = center_data.pop('slug')
            center, created = EducationalCenter.objects.update_or_create(
                slug=slug,
                defaults=center_data
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'Created: {center.name}'))
            else:
                updated_count += 1
                self.stdout.write(self.style.WARNING(f'Updated: {center.name}'))

        self.stdout.write(self.style.SUCCESS(f'\nTotal: {created_count} created, {updated_count} updated'))
